apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: deniskent-com-tls
  namespace: default
spec:
  secretName: deniskent-com
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: deniskent.com
  dnsNames:
    - deniskent.com
    - www.deniskent.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - deniskent.com
          - www.deniskent.com